version: '3'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: no
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - /Users/ariel/dev/projetos/java/api-cliente/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"